[package]
name = "splice-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = { version = "0.10.3", default-features = false }
pathfinding = { version = "3.0.5", default-features = false }
petgraph = { version = "0.6.0", default-features = false, features = ["stable_graph"] }
