[package]
name = "splice-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.52", default-features = false, features = ["std"] }
fixedbitset = { version = "0.4.1", default-features = false }
gtk = { version = "0.3.1", package = "gtk4", default-features = false }
itertools = { version = "0.10.3", default-features = false }
pathfinding = { version = "3.0.5", default-features = false }
petgraph = { version = "0.6.0", default-features = false, features = ["stable_graph"] }
relm4 = { version = "0.4.0-beta.3", default-features = false }
relm4-macros = { version = "0.4.0-beta.3", default-features = false }
tempfile = { version = "3.2.0", default-features = false }
